"""Emit the case-study appendix (case_studies.tex) from the result files.

The artist-gift dilemma of Section~\\ref{sec:results-two-levels} is
written out in full: the dilemma text, the two named actions, and the
three distinct winning responses side by side, each with the rule that
selected it, its raw score triple, its recommendation label and the
labeller's supporting quote.

Generating this rather than transcribing keeps the appendix in step with
aggregation_results/ and recommendations/.

Run:  python3 build_case_appendix.py
"""

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "case_studies.tex"
FRAMEWORKS = ("utilitarian", "deontological", "ubuntu")
RULES = ("baseline", "ec", "maximin", "nash")
RULE_NAME = {"baseline": "Baseline", "ec": "EC", "maximin": "Maximin",
             "nash": "Nash"}
COLOURS = ("c1", "c2", "c3")

CASES = [
    ("accepting_money_when_someone_gives_it_to_you",
     "Same action, three justifications",
     "Every winner carries \\texttt{TO\\_DO}, yet the three texts offer "
     "welfare arithmetic, relational repair, and guarded self-reliance as "
     "the reason for the same act."),
    ("cutting_contact_with_an_alcoholic",
     "Maximin dissenting",
     "The four rules return three different answers, and Maximin's winner "
     "is a refusal whose flat profile offends no judge, so the worst-case "
     "rule prefers a disclaimer to the substantive advice on offer."),
]

LIST_START = re.compile(r"^\s*(?:[-*\u2022]|\d+\.)\s+")


def esc(text: str) -> str:
    """LaTeX-escape a run of text. Markdown bold becomes \\textbf."""
    # The generator sometimes escapes its own brackets, e.g. \[a-url\].
    text = re.sub(r"\\([\[\]()])", r"\1", text)
    for a, b in (("\\", r"\textbackslash{}"), ("&", r"\&"), ("%", r"\%"),
                 ("$", r"\$"), ("#", r"\#"), ("_", r"\_"), ("{", r"\{"),
                 ("}", r"\}"), ("~", r"\textasciitilde{}"),
                 ("^", r"\textasciicircum{}")):
        text = text.replace(a, b)
    text = text.replace("’", "'").replace("‘", "'")
    text = text.replace("“", "``").replace("”", "''")
    text = text.replace("—", "---").replace("–", "--")
    text = re.sub(r"\*\*(.+?)\*\*", r"\\textbf{\1}", text)
    text = re.sub(r"(?<!\*)\*(?!\*)(.+?)(?<!\*)\*(?!\*)", r"\\emph{\1}", text)
    return text.replace("*", "")


def body(text: str) -> str:
    """Render a response, keeping paragraph and list-item breaks.

    The generator hard-wraps its output, so a newline is only meaningful
    where the next line opens a numbered or bulleted item.
    """
    out = []
    for para in text.split("\n\n"):
        lines, buf = [], []
        for line in para.split("\n"):
            if LIST_START.match(line) and buf:
                lines.append(" ".join(buf))
                buf = [line.strip()]
            else:
                buf.append(line.strip())
        if buf:
            lines.append(" ".join(buf))
        lines = [" ".join(ln.split()) for ln in lines if ln.strip()]
        if lines:
            out.append("\\\\\n".join(esc(ln) for ln in lines))
    return "\n\n".join(out)


lines = [
    "% Generated by build_case_appendix.py -- do not edit by hand.",
    "\\section{Divergence Case Studies}",
    "\\label{app:cases}",
    "",
    "The two dilemmas discussed in Sections~\\ref{sec:results-two-levels}",
    "and~\\ref{sec:results-why} are reproduced here in full. Each winning",
    "response is given with the rule that selected it, its raw scores under",
    "the utilitarian, deontological and Ubuntu judges, its recommendation",
    "label, and the supporting quote the labeller returned. Responses are",
    "verbatim apart from markdown emphasis.",
    "",
]

totals = []
for case_no, (slug, title, gloss) in enumerate(CASES):
    data = json.load((ROOT / "aggregation_results" / f"{slug}.json").open())
    quotes = {lab["id"]: lab.get("evidence", "").strip()
              for lab in json.load(
                  (ROOT / "recommendations" / f"{slug}.json").open())["labels"]}
    dilemma = data["dilemma"].split("\n\nGive a clear recommendation")[0]
    cands = {c["id"]: c for c in data["candidates"]}

    # One block per distinct winning response, listing every rule that chose it.
    order, chosen_by, label_of = [], {}, {}
    for rule in RULES:
        wid = data["winners"][rule]["id"]
        if wid not in chosen_by:
            order.append(wid)
            chosen_by[wid] = []
            label_of[wid] = data["winners"][rule]["recommendation"]
        chosen_by[wid].append(RULE_NAME[rule])

    if case_no:
        lines.append("\\clearpage")
    lines += [
        f"\\subsection{{{title}}}",
        "",
        "\\noindent\\textbf{Dilemma.} " + esc(dilemma.strip()),
        "",
        "\\noindent\\textbf{Named actions.} \\texttt{TO\\_DO} is "
        + esc(data["to_do_action"]) + ", \\texttt{NOT\\_TO\\_DO} is "
        + esc(data["not_to_do_action"]) + ".",
        "",
        "\\noindent\\textbf{What to look for.} " + gloss,
        "",
        "\\begin{tcbraster}[raster columns=3, raster column skip=5pt,",
        "                  raster equal height=rows, raster force size=false]",
    ]

    for wid, colour in zip(order, COLOURS):
        raw = cands[wid]["raw"]
        triple = ", ".join(str(raw[f]) for f in FRAMEWORKS)
        head = (" and ".join(chosen_by[wid]) + f" --- $({triple})$, "
                + "\\texttt{" + label_of[wid].replace("_", "\\_") + "}")
        lines.append(f"\\begin{{casebubble}}{{{head}}}{{{colour}dark}}"
                     f"{{{colour}light}}")
        if quotes.get(wid):
            lines += ["\\emph{Quote:} ``" + esc(quotes[wid]) + "''", "",
                      "\\medskip", ""]
        lines += [body(data["winner_texts"][str(wid)]), "\\end{casebubble}"]

    lines += ["\\end{tcbraster}", ""]
    totals.append((title, {w: len(data["winner_texts"][str(w)].split())
                           for w in order}))

OUT.write_text("\n".join(lines) + "\n")
print(f"wrote {OUT.name}: {len(CASES)} cases")
for title, words in totals:
    print(f"  {title}: {words}, total {sum(words.values())}")
